### ISSUE TITLE
Can't authenticate at Github

### ISSUE THREAD

**Issue by krisu-pl** [zeit/release#147]
It's the first time I try to use `release` tool. I run `release patch` command, then I get this in the console:

```
✔ Bumped version tag to 2.1.4
✔ Created release commit
✔ Tagged commit
✔ Pushed everything to remote
⠋ Opening GitHub authentication page(node:14153) UnhandledPromiseRejectionWarning: Error: Token authentication requires a token to be set
    at authenticate (/Users/krisu/.config/yarn/global/node_modules/@octokit/rest/lib/plugins/authentication/authenticate.js:25:15)
    at module.exports (/Users/krisu/.config/yarn/global/node_modules/release/lib/connect.js:127:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The browser opens a page which displays a code instead of running it:

![image](https://user-images.githubusercontent.com/7289999/50758100-75dc2480-1261-11e9-9685-9160b4ce5369.png)

**Comment by leo** [comment]
The error shown in the original issue is now fixed.
