### ISSUE TITLE
release-auth.now.sh is down

### ISSUE THREAD

**Issue by JonnyBurger** [zeit/release#52]
When going to `release-auth.now.sh`, I currently see an 502 error. The logs are:

```
▲ npm install
01/02/17 11:09:06 AM
Installing package micro@^6.1.0
01/02/17 11:09:07 AM
Installing package request@^2.79.0
01/02/17 11:09:07 AM
Installing package request-promise-native@^1.0.3
01/02/17 11:09:07 AM
Installing package xo@^0.17.1
01/02/17 11:09:16 AM
▲ npm start
01/02/17 11:09:17 AM
> Ready! Listening on http://0.0.0.0:5000
01/04/17 2:20:21 AM
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:284:9)
    at Function.Buffer.from (buffer.js:116:10)
    at new Buffer (buffer.js:95:17)
    at /home/nowuser/src/index.js:61:29
    at Generator.next (<anonymous>)
    at c (/home/nowuser/src/index.js:94:99)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by leo** [comment]
Should work now!
